
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-6pm-2
owner: ucsb-cs156-w24
repo_name: team01-w24-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ1NTE5MDIy","is_bot":false,"login":"mbharti12","name":"Mihir B"},"headRefName":"Mihir-Jokes-Controller","number":24,"title":"Add Joke Controller and Test","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-2/pull/24"},{"author":{"id":"MDQ6VXNlcjQ1NTE5MDIy","is_bot":false,"login":"mbharti12","name":"Mihir B"},"headRefName":"Mihir-Jokes","number":23,"title":"Add Joke Service and Test","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-2/pull/23"},{"author":{"id":"U_kgDOB2_BEg","is_bot":false,"login":"kjlee2504","name":"Kevin Lee"},"headRefName":"Kevin-Tides-Controller","number":19,"title":"KL - Completed \"Add Tides and Controller\" task","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-2/pull/19"},{"author":{"id":"U_kgDOB2_BEg","is_bot":false,"login":"kjlee2504","name":"Kevin Lee"},"headRefName":"Kevin-Tides","number":18,"title":"KL - Completed \"Add Tides Service and Tests\" Task","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-2/pull/18"}]
