
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-6pm-2
owner: ucsb-cs156-w24
repo_name: team01-w24-6pm-2
pull_requests: [{"author":{"id":"U_kgDOB3Dxlg","is_bot":false,"login":"DemirInce","name":""},"headRefName":"Demir-HomeController","number":27,"title":"Demir Home Controller and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-2/pull/27"},{"author":{"id":"MDQ6VXNlcjkxMjk1MDY3","is_bot":false,"login":"vincentlinzhu","name":"Vincent Zhu"},"headRefName":"Vincent-Holiday","number":26,"title":"Add Public Holiday Service, Service Tests, Controller, and Controller Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-2/pull/26"}]
